name: plant_app
description: "A Flutter plant shop UI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/plant_icon.png
    - assets/images/alovera.jpg
    - assets/images/cactus.jpg
    - assets/images/ficas.jpg
